### ISSUE TITLE
It's causing an error

### ISSUE THREAD

**Issue by ludiusvox** [Shopify/vscode-shadowenv#23]
Type: <b>Bug</b>

Just booting up VS-vode

Extension version: 0.1.1
VS Code version: Code 1.77.3 (Universal) (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:19:37.325Z)
OS version: Darwin arm64 22.4.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|37, 12, 6|
|Memory (System)|8.00GB (0.50GB free)|
|Process Argv|--crash-reporter-id 9541f94c-63c0-45f0-91e8-342e5f34951d|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
nodejswelcome1cf:30587006
2e4cg342:30602488
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
a9j8j154:30646983
vsccsb:30705552
azdwalk:30687957
pythonms35:30701012
pythonfmttextcf:30716743

```

</details>

**Comment by donk-shopify** [comment]
Can you tell us more details about the issue? How is this impacting your work? How could we replicate it?

**Comment by ludiusvox** [comment]
I think the app was installed so that I could play with shopify ruby dashboards, and ended up having problems customizing it.  And Ruby has had some updates since then, I would recommend trying to update the shopify ruby kits on github probably in the build files.  I just have it disabled at this point.
