### ISSUE TITLE
Shadowenv not always executed when opening a terminal

### ISSUE THREAD

**Issue by mathieushopify** [Shopify/vscode-shadowenv#4]
Scenarios:
- Open VSCode from the Dock => Result: works as expected
- Open VSCode from command line using `code .` ==> Result: Shadowenv not initialized properly need to `cd .. & cd <project>` to initialize.
- Split terminal ==> Result: Shadowenv not initialized properly need to `cd .. & cd <project>` to initialize.

Looks like we're missing some triggers for some situations

**Comment by douglas** [comment]
Just to say that I can reproduce the reported problem here as well with the extension built from master.

**Comment by shanesmith** [comment]
This PR could potentially address your issue: https://github.com/Shopify/vscode-shadowenv/pull/7
